### ISSUE TITLE
Error: "failed to activate bufferpool"

### ISSUE THREAD

**Issue by CsatiZoltan** [keshavbhatt/gifex#1]
On Ubuntu 18.04 LTS.

![Error](https://user-images.githubusercontent.com/12742890/83494087-08641000-a4b6-11ea-84c1-ce15d676de6e.png)

**Comment by keshavbhatt** [comment]
Hi, thanks for reporting.
You using x11 session ?
Gifex for now support only x11 session.
Also what happen when you record video ?
looking at the video clipper dialog it seems like the video is empty.(see duration)

**Comment by CsatiZoltan** [comment]
Hi!

Yes, I use X11.
This is strange. Now, apart from the Qt warning `QWidget::paintEngine: Should no longer be called`, *Gifex* works fine. I have no idea what changed since the last time. I propose keeping this issue open for a day or so, and if I don't experience this problem, I will close it.

**Comment by keshavbhatt** [comment]
> QWidget::paintEngine: Should no longer be called
This is just a warning from Qt's paint engine coming from QMediaPlayer library, I cannot do anything to prevent that.
