### ISSUE TITLE
It doesn't work any more. Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by cgcgcgcgcg** [keshavbhatt/gifex#2]
It used to but this is what I get when running from a terminal:
`[k@kw ~]$ gifex
Gtk-Message: 12:16:24.271: Failed to load module "canberra-gtk-module"

(gifex:76868): dbind-WARNING **: 12:16:24.304: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
`
All canberra packages are installed on my Manjaro, I suspect that module should be embedded in the snap.
When I try to capture this is shown:
![ksnip_20200627-121639](https://user-images.githubusercontent.com/38960370/85919004-5deecb00-b870-11ea-8573-7a492dbe0820.png)

**Comment by keshavbhatt** [comment]
i will look into this. thanks for reporting.

**Comment by keshavbhatt** [comment]
this issue is not due to canberra-gtk-module 
issue is with "slop" which is refusing to start.
