### ISSUE TITLE
How do I read the source code?

### ISSUE THREAD

**Issue by MatthewForrester** [keshavbhatt/gifex#4]
Apologies, this is probably a very newbie question.

This repository says that is licensed under GPL 2.0. But I can't find the source code. It just appears to be a snap package for [a binary copy of gifex binary](https://github.com/keshavbhatt/gifex/blob/master/snap_launcher/bin/gifex), without providing the source code.

**Comment by keshavbhatt** [comment]
Here: https://github.com/keshavbhatt/gifex/tree/master/src
