### ISSUE TITLE
Perfect but some problems.

### ISSUE THREAD

**Issue by KaiLovesJB** [keshavbhatt/gifex#5]
I feel like the program is amazing, I have tried so many on Linux and none of them are good except this one but it should allow you to set it to 60 fps and use ffmpeg as it makes gif files a lot smaller, apart from that keep up the good work!

**Comment by keshavbhatt** [comment]
usually gif images are very low in frame rate, hence 60 fps makes no sense here. 
additionally gif image with 60 fps will be huge in size and will take lot of time to compile. 
App uses ffmpeg see source code.

Thanks :)
